// Phone Number Validator - Validates international phone numbers using custom country codes array
// Example usage with your country codes array

export type CountryCode = {
  iso: string;
  country: string;
  code: string;
  phoneLength: number | number[];
};

export const countryCodes: CountryCode[] = [
  {
    iso: "AG",
    country: "Antigua and Barbuda",
    code: "1-268",
    phoneLength: 10,
  },
  {
    iso: "AI",
    country: "Anguilla",
    code: "1-264",
    phoneLength: 10,
  },
  {
    iso: "AS",
    country: "American Samoa",
    code: "1-684",
    phoneLength: 10,
  },
  {
    iso: "BB",
    country: "Barbados",
    code: "1-246",
    phoneLength: 10,
  },
  {
    iso: "BM",
    country: "Bermuda",
    code: "1-441",
    phoneLength: 10,
  },
  {
    iso: "BS",
    country: "Bahamas",
    code: "1-242",
    phoneLength: 10,
  },
  {
    iso: "DM",
    country: "Dominica",
    code: "1-767",
    phoneLength: 10,
  },
  {
    iso: "DO",
    country: "Dominican Republic",
    code: "1-809",
    phoneLength: 10,
  },
  {
    iso: "GD",
    country: "Grenada",
    code: "1-473",
    phoneLength: 10,
  },
  {
    iso: "GU",
    country: "Guam",
    code: "1-671",
    phoneLength: 10,
  },
  {
    iso: "JM",
    country: "Jamaica",
    code: "1-876",
    phoneLength: 10,
  },
  {
    iso: "KN",
    country: "Saint Kitts and Nevis",
    code: "1-869",
    phoneLength: 10,
  },
  {
    iso: "KY",
    country: "Cayman Islands",
    code: "1-345",
    phoneLength: 7,
  },
  {
    iso: "LC",
    country: "Saint Lucia",
    code: "1-758",
    phoneLength: 7,
  },
  {
    iso: "MP",
    country: "Northern Mariana Islands",
    code: "1-670",
    phoneLength: 7,
  },
  {
    iso: "MS",
    country: "Montserrat",
    code: "1-664",
    phoneLength: 10,
  },
  {
    iso: "SX",
    country: "Sint Maarten (Dutch part)",
    code: "1-721",
    phoneLength: 10,
  },
  {
    iso: "TC",
    country: "Turks and Caicos Islands",
    code: "1-649",
    phoneLength: 10,
  },
  {
    iso: "TT",
    country: "Trinidad and Tobago",
    code: "1-868",
    phoneLength: 7,
  },
  {
    iso: "VC",
    country: "Saint Vincent and the Grenadines",
    code: "1-784",
    phoneLength: 7,
  },
  {
    iso: "VG",
    country: "British Virgin Islands",
    code: "1-284",
    phoneLength: 7,
  },
  {
    iso: "VI",
    country: "US Virgin Islands",
    code: "1-340",
    phoneLength: 10,
  },
  {
    iso: "AD",
    country: "Andorra",
    code: "376",
    phoneLength: 6,
  },
  {
    iso: "AE",
    country: "United Arab Emirates",
    code: "971",
    phoneLength: 9,
  },
  {
    iso: "AL",
    country: "Albania",
    code: "355",
    phoneLength: 9,
  },
  {
    iso: "AM",
    country: "Armenia",
    code: "374",
    phoneLength: 6,
  },
  {
    iso: "AO",
    country: "Angola",
    code: "244",
    phoneLength: 9,
  },
  {
    iso: "AQ",
    country: "Antarctica",
    code: "672",
    phoneLength: 6,
  },
  {
    iso: "AW",
    country: "Aruba",
    code: "297",
    phoneLength: 7,
  },
  {
    iso: "AX",
    country: "Alland Islands",
    code: "358",
    phoneLength:[7,10]
  },
  {
    iso: "AZ",
    country: "Azerbaijan",
    code: "994",
    phoneLength: 9,
  },
  {
    iso: "BA",
    country: "Bosnia and Herzegovina",
    code: "387",
    phoneLength: 8,
  },
  {
    iso: "BD",
    country: "Bangladesh",
    code: "880",
    phoneLength: 10,
  },
  {
    iso: "BF",
    country: "Burkina Faso",
    code: "226",
    phoneLength: 8,
  },
  {
    iso: "BG",
    country: "Bulgaria",
    code: "359",
    phoneLength: 9,
  },
  {
    iso: "BH",
    country: "Bahrain",
    code: "973",
    phoneLength: 8,
  },
  {
    iso: "BI",
    country: "Burundi",
    code: "257",
    phoneLength: 8,
  },
  {
    iso: "BJ",
    country: "Benin",
    code: "229",
    phoneLength: 8,
  },
  {
    iso: "BL",
    country: "Saint Barthelemy",
    code: "590",
    phoneLength: 9,
  },
  {
    iso: "BN",
    country: "Brunei Darussalam",
    code: "673",
    phoneLength: 7,
  },
  {
    iso: "BO",
    country: "Bolivia",
    code: "591",
    phoneLength: 9,
  },
  {
    iso: "BT",
    country: "Bhutan",
    code: "975",
    phoneLength: 7,
  },
  {
    iso: "BW",
    country: "Botswana",
    code: "267",
    phoneLength: 7,
  },
  {
    iso: "BY",
    country: "Belarus",
    code: "375",
    phoneLength: 9,
  },
  {
    iso: "BZ",
    country: "Belize",
    code: "501",
    phoneLength: 7,
  },
  {
    iso: "CD",
    country: "Congo, Democratic Republic of the",
    code: "243",
    phoneLength: 7,
  },
  {
    iso: "CF",
    country: "Central African Republic",
    code: "236",
    phoneLength: 8,
  },
  {
    iso: "CG",
    country: "Congo, Republic of the",
    code: "242",
    phoneLength: 9,
  },
  {
    iso: "CI",
    country: "Cote d'Ivoire",
    code: "225",
    phoneLength: 8,
  },
  {
    iso: "CK",
    country: "Cook Islands",
    code: "682",
    phoneLength: 5,
  },
  {
    iso: "CM",
    country: "Cameroon",
    code: "237",
    phoneLength: 9,
  },
  {
    iso: "CR",
    country: "Costa Rica",
    code: "506",
    phoneLength: 8,
  },
  {
    iso: "CV",
    country: "Cape Verde",
    code: "238",
    phoneLength: 7,
  },
  {
    iso: "CW",
    country: "Curacao",
    code: "599",
    phoneLength: 7,
  },
  {
    iso: "CY",
    country: "Cyprus",
    code: "357",
    phoneLength: 8,
  },
  {
    iso: "CZ",
    country: "Czech Republic",
    code: "420",
    phoneLength: 9,
  },
  {
    iso: "DJ",
    country: "Djibouti",
    code: "253",
    phoneLength: 10,
  },
  {
    iso: "DZ",
    country: "Algeria",
    code: "213",
    phoneLength: 9,
  },
  {
    iso: "EC",
    country: "Ecuador",
    code: "593",
    phoneLength: 9,
  },
  {
    iso: "EE",
    country: "Estonia",
    code: "372",
    phoneLength: 8,
  },
  {
    iso: "EH",
    country: "Western Sahara",
    code: "212",
    phoneLength: 9,
  },
  {
    iso: "ER",
    country: "Eritrea",
    code: "291",
    phoneLength: 7,
  },
  {
    iso: "ET",
    country: "Ethiopia",
    code: "251",
    phoneLength: 9,
  },
  {
    iso: "FI",
    country: "Finland",
    code: "358",
    phoneLength: [9, 11],
  },
  {
    iso: "FJ",
    country: "Fiji",
    code: "679",
    phoneLength: 7,
  },
  {
    iso: "FK",
    country: "Falkland Islands (Malvinas)",
    code: "500",
    phoneLength: 5,
  },
  {
    iso: "FM",
    country: "Micronesia, Federated States of",
    code: "691",
    phoneLength: 7,
  },
  {
    iso: "FO",
    country: "Faroe Islands",
    code: "298",
    phoneLength: 5,
  },
  {
    iso: "GA",
    country: "Gabon",
    code: "241",
    phoneLength: 7,
  },
  {
    iso: "GE",
    country: "Georgia",
    code: "995",
    phoneLength: 9,
  },
  {
    iso: "GF",
    country: "French Guiana",
    code: "594",
    phoneLength: 9,
  },
  {
    iso: "GH",
    country: "Ghana",
    code: "233",
    phoneLength: 9,
  },
  {
    iso: "GI",
    country: "Gibraltar",
    code: "350",
    phoneLength: 8,
  },
  {
    iso: "GL",
    country: "Greenland",
    code: "299",
    phoneLength: 6,
  },
  {
    iso: "GM",
    country: "Gambia",
    code: "220",
    phoneLength: 7,
  },
  {
    iso: "GN",
    country: "Guinea",
    code: "224",
    phoneLength: 9,
  },
  {
    iso: "GP",
    country: "Guadeloupe",
    code: "590",
    phoneLength: 9,
  },
  {
    iso: "GQ",
    country: "Equatorial Guinea",
    code: "240",
    phoneLength: 9,
  },
  {
    iso: "GS",
    country: "South Georgia and the South Sandwich Islands",
    code: "500",
    phoneLength: 5,
  },
  {
    iso: "GT",
    country: "Guatemala",
    code: "502",
    phoneLength: 8,
  },
  {
    iso: "GW",
    country: "Guinea-Bissau",
    code: "245",
    phoneLength: 9,
  },
  {
    iso: "GY",
    country: "Guyana",
    code: "592",
    phoneLength: 7,
  },
  {
    iso: "HK",
    country: "Hong Kong",
    code: "852",
    phoneLength: 8,
  },
  {
    iso: "HM",
    country: "Heard Island and McDonald Islands",
    code: "672",
    phoneLength: 10,
  },
  {
    iso: "HN",
    country: "Honduras",
    code: "504",
    phoneLength: 8,
  },
  {
    iso: "HR",
    country: "Croatia",
    code: "385",
    phoneLength: 9,
  },
  {
    iso: "HT",
    country: "Haiti",
    code: "509",
    phoneLength: 8,
  },
  {
    iso: "IE",
    country: "Ireland",
    code: "353",
    phoneLength: 9,
  },
  {
    iso: "IL",
    country: "Israel",
    code: "972",
    phoneLength: 9,
  },
  {
    iso: "IO",
    country: "British Indian Ocean Territory",
    code: "246",
    phoneLength: 7,
  },
  {
    iso: "IQ",
    country: "Iraq",
    code: "964",
    phoneLength: 10,
  },
  {
    iso: "IS",
    country: "Iceland",
    code: "354",
    phoneLength: 7,
  },
  {
    iso: "JO",
    country: "Jordan",
    code: "962",
    phoneLength: [8, 9],
  },
  {
    iso: "KE",
    country: "Kenya",
    code: "254",
    phoneLength: 10,
  },
  {
    iso: "KG",
    country: "Kyrgyzstan",
    code: "996",
    phoneLength: 9,
  },
  {
    iso: "KH",
    country: "Cambodia",
    code: "855",
    phoneLength: 9,
  },
  {
    iso: "KI",
    country: "Kiribati",
    code: "686",
    phoneLength: 8,
  },
  {
    iso: "KM",
    country: "Comoros",
    code: "269",
    phoneLength: 7,
  },
  {
    iso: "KP",
    country: "Korea, Democratic People's Republic of",
    code: "850",
    phoneLength: [4, 6, 7, 13],
  },
  {
    iso: "KW",
    country: "Kuwait",
    code: "965",
    phoneLength: 8,
  },
  {
    iso: "LA",
    country: "Lao People's Democratic Republic",
    code: "856",
    phoneLength: [8, 9],
  },
  {
    iso: "LB",
    country: "Lebanon",
    code: "961",
    phoneLength: [7, 8],
  },
  {
    iso: "LI",
    country: "Liechtenstein",
    code: "423",
    phoneLength: 7,
  },
  {
    iso: "LR",
    country: "Liberia",
    code: "231",
    phoneLength: [8, 9],
  },
  {
    iso: "LS",
    country: "Lesotho",
    code: "266",
    phoneLength: 8,
  },
  {
    iso: "LT",
    country: "Lithuania",
    code: "370",
    phoneLength: 8,
  },
  {
    iso: "LU",
    country: "Luxembourg",
    code: "352",
    phoneLength: 9,
  },
  {
    iso: "LV",
    country: "Latvia",
    code: "371",
    phoneLength: 8,
  },
  {
    iso: "LY",
    country: "Libya",
    code: "218",
    phoneLength: 10,
  },
  {
    iso: "MA",
    country: "Morocco",
    code: "212",
    phoneLength: 9,
  },
  {
    iso: "MC",
    country: "Monaco",
    code: "377",
    phoneLength: 8,
  },
  {
    iso: "MD",
    country: "Moldova, Republic of",
    code: "373",
    phoneLength: 8,
  },
  {
    iso: "ME",
    country: "Montenegro",
    code: "382",
    phoneLength: 8,
  },
  {
    iso: "MF",
    country: "Saint Martin (French part)",
    code: "590",
    phoneLength: 6,
  },
  {
    iso: "MG",
    country: "Madagascar",
    code: "261",
    phoneLength: 7,
  },
  {
    iso: "MH",
    country: "Marshall Islands",
    code: "692",
    phoneLength: 7,
  },
  {
    iso: "MK",
    country: "Macedonia, the Former Yugoslav Republic of",
    code: "389",
    phoneLength: 8,
  },
  {
    iso: "ML",
    country: "Mali",
    code: "223",
    phoneLength: 8,
  },
  {
    iso: "MN",
    country: "Mongolia",
    code: "976",
    phoneLength: 8,
  },
  {
    iso: "MO",
    country: "Macao",
    code: "853",
    phoneLength: 8,
  },
  {
    iso: "MQ",
    country: "Martinique",
    code: "596",
    phoneLength: 9,
  },
  {
    iso: "MR",
    country: "Mauritania",
    code: "222",
    phoneLength: 8,
  },
  {
    iso: "MT",
    country: "Malta",
    code: "356",
    phoneLength: 8,
  },
  {
    iso: "MU",
    country: "Mauritius",
    code: "230",
    phoneLength: 8,
  },
  {
    iso: "MV",
    country: "Maldives",
    code: "960",
    phoneLength: 7,
  },
  {
    iso: "MW",
    country: "Malawi",
    code: "265",
    phoneLength: [7, 8, 9],
  },
  {
    iso: "MZ",
    country: "Mozambique",
    code: "258",
    phoneLength: 12,
  },
  {
    iso: "NA",
    country: "Namibia",
    code: "264",
    phoneLength: 7,
  },
  {
    iso: "NC",
    country: "New Caledonia",
    code: "687",
    phoneLength: 6,
  },
  {
    iso: "NE",
    country: "Niger",
    code: "227",
    phoneLength: 8,
  },
  {
    iso: "NF",
    country: "Norfolk Island",
    code: "672",
    phoneLength: 6,
  },
  {
    iso: "NG",
    country: "Nigeria",
    code: "234",
    phoneLength: 8,
  },
  {
    iso: "NI",
    country: "Nicaragua",
    code: "505",
    phoneLength: 8,
  },
  {
    iso: "NP",
    country: "Nepal",
    code: "977",
    phoneLength: 10,
  },
  {
    iso: "NR",
    country: "Nauru",
    code: "674",
    phoneLength: 7,
  },
  {
    iso: "NU",
    country: "Niue",
    code: "683",
    phoneLength: 4,
  },
  {
    iso: "OM",
    country: "Oman",
    code: "968",
    phoneLength: 8,
  },
  {
    iso: "PA",
    country: "Panama",
    code: "507",
    phoneLength: 8,
  },
  {
    iso: "PF",
    country: "French Polynesia",
    code: "689",
    phoneLength: 8,
  },
  {
    iso: "PG",
    country: "Papua New Guinea",
    code: "675",
    phoneLength: 8,
  },
  {
    iso: "PM",
    country: "Saint Pierre and Miquelon",
    code: "508",
    phoneLength: 6,
  },
  {
    iso: "PN",
    country: "Pitcairn",
    code: "870",
    phoneLength: 9,
  },
  {
    iso: "PS",
    country: "Palestine, State of",
    code: "970",
    phoneLength: 9,
  },
  {
    iso: "PT",
    country: "Portugal",
    code: "351",
    phoneLength: 9,
  },
  {
    iso: "PW",
    country: "Palau",
    code: "680",
    phoneLength: 7,
  },
  {
    iso: "PY",
    country: "Paraguay",
    code: "595",
    phoneLength: 9,
  },
  {
    iso: "QA",
    country: "Qatar",
    code: "974",
    phoneLength: 8,
  },
  {
    iso: "RE",
    country: "Reunion",
    code: "262",
    phoneLength: 10,
  },
  {
    iso: "RS",
    country: "Serbia",
    code: "381",
    phoneLength: 9,
  },
  {
    iso: "RW",
    country: "Rwanda",
    code: "250",
    phoneLength: 9,
  },
  {
    iso: "SA",
    country: "Saudi Arabia",
    code: "966",
    phoneLength: 9,
  },
  {
    iso: "SB",
    country: "Solomon Islands",
    code: "677",
    phoneLength: 7,
  },
  {
    iso: "SC",
    country: "Seychelles",
    code: "248",
    phoneLength: 7,
  },
  {
    iso: "SD",
    country: "Sudan",
    code: "249",
    phoneLength: 7,
  },
  {
    iso: "SH",
    country: "Saint Helena",
    code: "290",
    phoneLength: 4,
  },
  {
    iso: "SI",
    country: "Slovenia",
    code: "386",
    phoneLength: 9,
  },
  {
    iso: "SK",
    country: "Slovakia",
    code: "421",
    phoneLength: 9,
  },
  {
    iso: "SL",
    country: "Sierra Leone",
    code: "232",
    phoneLength: 8,
  },
  {
    iso: "SM",
    country: "San Marino",
    code: "378",
    phoneLength: 10,
  },
  {
    iso: "SN",
    country: "Senegal",
    code: "221",
    phoneLength: 9,
  },
  {
    iso: "SO",
    country: "Somalia",
    code: "252",
    phoneLength: [8, 9],
  },
  {
    iso: "SR",
    country: "Suriname",
    code: "597",
    phoneLength: [6, 7],
  },
  {
    iso: "SS",
    country: "South Sudan",
    code: "211",
    phoneLength: 7,
  },
  {
    iso: "ST",
    country: "Sao Tome and Principe",
    code: "239",
    phoneLength: 7,
  },
  {
    iso: "SV",
    country: "El Salvador",
    code: "503",
    phoneLength: 8,
  },
  {
    iso: "SY",
    country: "Syrian Arab Republic",
    code: "963",
    phoneLength: 7,
  },
  {
    iso: "SZ",
    country: "Swaziland",
    code: "268",
    phoneLength: 8,
  },
  {
    iso: "TD",
    country: "Chad",
    code: "235",
    phoneLength: 6,
  },
  {
    iso: "TF",
    country: "French Southern Territories",
    code: "262",
    phoneLength: 10,
  },
  {
    iso: "TG",
    country: "Togo",
    code: "228",
    phoneLength: 8,
  },
  {
    iso: "TJ",
    country: "Tajikistan",
    code: "992",
    phoneLength: 9,
  },
  {
    iso: "TK",
    country: "Tokelau",
    code: "690",
    phoneLength: 5,
  },
  {
    iso: "TL",
    country: "Timor-Leste",
    code: "670",
    phoneLength: 7,
  },
  {
    iso: "TM",
    country: "Turkmenistan",
    code: "993",
    phoneLength: 8,
  },
  {
    iso: "TN",
    country: "Tunisia",
    code: "216",
    phoneLength: 8,
  },
  {
    iso: "TO",
    country: "Tonga",
    code: "676",
    phoneLength: 5,
  },
  {
    iso: "TV",
    country: "Tuvalu",
    code: "688",
    phoneLength: 5,
  },
  {
    iso: "TW",
    country: "Taiwan, Province of China",
    code: "886",
    phoneLength: 9,
  },
  {
    iso: "TZ",
    country: "United Republic of Tanzania",
    code: "255",
    phoneLength: 7,
  },
  {
    iso: "UA",
    country: "Ukraine",
    code: "380",
    phoneLength: 9,
  },
  {
    iso: "UG",
    country: "Uganda",
    code: "256",
    phoneLength: 7,
  },
  {
    iso: "UY",
    country: "Uruguay",
    code: "598",
    phoneLength: 8,
  },
  {
    iso: "UZ",
    country: "Uzbekistan",
    code: "998",
    phoneLength: 9,
  },
  {
    iso: "VA",
    country: "Holy See (Vatican City State)",
    code: "379",
    phoneLength: 10,
  },
  {
    iso: "VU",
    country: "Vanuatu",
    code: "678",
    phoneLength: 5,
  },
  {
    iso: "WF",
    country: "Wallis and Futuna",
    code: "681",
    phoneLength: 6,
  },
  {
    iso: "WS",
    country: "Samoa",
    code: "685",
    phoneLength: [5, 6, 7],
  },
  {
    iso: "XK",
    country: "Kosovo",
    code: "383",
    phoneLength: 8,
  },
  {
    iso: "YE",
    country: "Yemen",
    code: "967",
    phoneLength: 9,
  },
  {
    iso: "YT",
    country: "Mayotte",
    code: "262",
    phoneLength: 9,
  },
  {
    iso: "ZM",
    country: "Zambia",
    code: "260",
    phoneLength: 9,
  },
  {
    iso: "ZW",
    country: "Zimbabwe",
    code: "263",
    phoneLength: 9,
  },
  {
    iso: "AF",
    country: "Afghanistan",
    code: "93",
    phoneLength: 9,
  },
  {
    iso: "AR",
    country: "Argentina",
    code: "54",
    phoneLength: [6, 7, 8],
  },
  {
    iso: "AT",
    country: "Austria",
    code: "43",
    phoneLength: [10, 11],
  },
  {
    iso: "AU",
    country: "Australia",
    code: "61",
    phoneLength: 9,
  },
  {
    iso: "BE",
    country: "Belgium",
    code: "32",
    phoneLength: 9,
  },
  {
    iso: "BR",
    country: "Brazil",
    code: "55",
    phoneLength: 11,
  },
  {
    iso: "BV",
    country: "Bouvet Island",
    code: "47",
    phoneLength: 10,
  },
  {
    iso: "CC",
    country: "Cocos (Keeling) Islands",
    code: "61",
    phoneLength: 10,
  },
  {
    iso: "CH",
    country: "Switzerland",
    code: "41",
    phoneLength: 9,
  },
  {
    iso: "CL",
    country: "Chile",
    code: "56",
    phoneLength: 9,
  },
  {
    iso: "CN",
    country: "China",
    code: "86",
    phoneLength: 11,
  },
  {
    iso: "CO",
    country: "Colombia",
    code: "57",
    phoneLength: 10,
  },
  {
    iso: "CU",
    country: "Cuba",
    code: "53",
    phoneLength: 8,
  },
  {
    iso: "CX",
    country: "Christmas Island",
    code: "61",
    phoneLength: 9,
  },
  {
    iso: "DE",
    country: "Germany",
    code: "49",
    phoneLength: 10,
  },
  {
    iso: "DK",
    country: "Denmark",
    code: "45",
    phoneLength: 8,
  },
  {
    iso: "EG",
    country: "Egypt",
    code: "20",
    phoneLength: 10,
  },
  {
    iso: "ES",
    country: "Spain",
    code: "34",
    phoneLength: 9,
  },
  {
    iso: "FR",
    country: "France",
    code: "33",
    phoneLength: 9,
  },
  {
    iso: "GB",
    country: "United Kingdom",
    code: "44",
    phoneLength: 10,
  },
  {
    iso: "GG",
    country: "Guernsey",
    code: "44",
    phoneLength: 10,
  },
  {
    iso: "GR",
    country: "Greece",
    code: "30",
    phoneLength: 10,
  },
  {
    iso: "HU",
    country: "Hungary",
    code: "36",
    phoneLength: 9,
  },
  {
    iso: "ID",
    country: "Indonesia",
    code: "62",
    phoneLength: 11,
  },
  {
    iso: "IM",
    country: "Isle of Man",
    code: "44",
    phoneLength: 10,
  },
  {
    iso: "IN",
    country: "India",
    code: "91",
    phoneLength: 10,
  },
  {
    iso: "IR",
    country: "Iran, Islamic Republic of",
    code: "98",
    phoneLength: 11,
  },
  {
    iso: "IT",
    country: "Italy",
    code: "39",
    phoneLength: 10,
  },
  {
    iso: "JE",
    country: "Jersey",
    code: "44",
    phoneLength: 10,
  },
  {
    iso: "JP",
    country: "Japan",
    code: "81",
    phoneLength: 10,
  },
  {
    iso: "KR",
    country: "Korea, Republic of",
    code: "82",
    phoneLength: [7, 8],
  },
  {
    iso: "LK",
    country: "Sri Lanka",
    code: "94",
    phoneLength: 7,
  },
  {
    iso: "MM",
    country: "Myanmar",
    code: "95",
    phoneLength: [7, 10],
  },
  {
    iso: "MX",
    country: "Mexico",
    code: "52",
    phoneLength: 10,
  },
  {
    iso: "MY",
    country: "Malaysia",
    code: "60",
    phoneLength: 7,
  },
  {
    iso: "NL",
    country: "Netherlands",
    code: "31",
    phoneLength: 9,
  },
  {
    iso: "NO",
    country: "Norway",
    code: "47",
    phoneLength: 8,
  },
  {
    iso: "NZ",
    country: "New Zealand",
    code: "64",
    phoneLength: [8, 9],
  },
  {
    iso: "PE",
    country: "Peru",
    code: "51",
    phoneLength: 9,
  },
  {
    iso: "PH",
    country: "Philippines",
    code: "63",
    phoneLength: 10,
  },
  {
    iso: "PK",
    country: "Pakistan",
    code: "92",
    phoneLength: 10,
  },
  {
    iso: "PL",
    country: "Poland",
    code: "48",
    phoneLength: 9,
  },
  {
    iso: "RO",
    country: "Romania",
    code: "40",
    phoneLength: 10,
  },
  {
    iso: "SE",
    country: "Sweden",
    code: "46",
    phoneLength: 7,
  },
  {
    iso: "SG",
    country: "Singapore",
    code: "65",
    phoneLength: 8,
  },
  {
    iso: "SJ",
    country: "Svalbard and Jan Mayen",
    code: "47",
    phoneLength: 8,
  },
  {
    iso: "TH",
    country: "Thailand",
    code: "66",
    phoneLength: 9,
  },
  {
    iso: "TR",
    country: "Turkey",
    code: "90",
    phoneLength: 11,
  },
  {
    iso: "VE",
    country: "Venezuela",
    code: "58",
    phoneLength: 7,
  },
  {
    iso: "VN",
    country: "Vietnam",
    code: "84",
    phoneLength: 9,
  },
  {
    iso: "ZA",
    country: "South Africa",
    code: "27",
    phoneLength: 9,
  },
  {
    iso: "CA",
    country: "Canada",
    code: "1",
    phoneLength: 10,
  },
  {
    iso: "KZ",
    country: "Kazakhstan",
    code: "7",
    phoneLength: 10,
  },
  {
    iso: "PR",
    country: "Puerto Rico",
    code: "1",
    phoneLength: 10,
  },
  {
    iso: "RU",
    country: "Russian Federation",
    code: "7",
    phoneLength: 10,
  },
  {
    iso: "US",
    country: "United States",
    code: "1",
    phoneLength: 10,
  },
];