# Nixpacks Configuration for Connecta
# Static site deployment configuration

[phases.setup]
nixPkgs = ["nodejs-20_x", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "echo 'Static site built successfully'"
