# Nixpacks Configuration for Connecta
# Used by Coolify for building and deploying

[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = ""

[staticAssets]
dir = "dist"
